export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const SAVE_NOTES_STATE = 'SAVE_NOTES_STATE';
export const LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS';
export const SAVE_NOTE_SUCCESS = 'SAVE_NOTE_SUCCESS';
export const NOTE_SELECTED = 'NOTE_SELECTED';